apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: devopscloudrucamp
  labels:
    app: cloudcamp-test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudcamp-test-app
  template:
    metadata:
      labels:
        app: cloudcamp-test-app
    spec:
      containers:
        - name: webapp
          image: danil2286/cloudcamp-devops:latest
          imagePullPolicy: Always
          env:
            - name: AUTHOR
              value: "Danila Gudynin"
            - name: UUID
              value: "bc3b0e31-edbf-464b-bc64-b71083083fb8"
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
