apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: devopscloudrucamp
spec:
  type: ClusterIP
  selector:
    app: cloudcamp-test-app
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
